-- Seed data (products, categories, coupons, testimonials, store locations)
-- Safe to re-run: rows are matched on their natural key.

insert into public.categories (slug,name,description,image,is_active) values ('for-her','For Her','Soft florals, warm vanillas and powdery musks composed for the modern woman.','/e3a59ab0-5771-43a5-9155-550dc7a4670a.jpg',true) on conflict (slug) do nothing;
insert into public.categories (slug,name,description,image,is_active) values ('for-him','For Him','Woody, spiced and leather-led scents with quiet confidence.','/114886d9-688e-4210-83f9-bea62727678e.jpg',true) on conflict (slug) do nothing;
insert into public.categories (slug,name,description,image,is_active) values ('unisex','Unisex','Shared signatures — amber, oud and clean citrus for everyone.','/faebb927-96b3-4242-b079-a3a54a804b67.jpg',true) on conflict (slug) do nothing;
insert into public.categories (slug,name,description,image,is_active) values ('designer-perfume','Designer Perfume','Authentic designer houses, sourced and sealed.','/faebb927-96b3-4242-b079-a3a54a804b67.jpg',true) on conflict (slug) do nothing;
insert into public.categories (slug,name,description,image,is_active) values ('body-mist','Body Mist','Light, refreshing veils of scent for everyday wear.','/13d0cd31-7b4e-49b1-a1c2-aa624fa6ae1d.jpg',true) on conflict (slug) do nothing;
insert into public.categories (slug,name,description,image,is_active) values ('body-sprays','Body Sprays','All-day freshness with a generous, long-lasting spray.','/13d0cd31-7b4e-49b1-a1c2-aa624fa6ae1d.jpg',true) on conflict (slug) do nothing;
insert into public.categories (slug,name,description,image,is_active) values ('perfume-oils','Perfume Oils','Concentrated, alcohol-free oils that bloom on the skin.','/dfba970f-1742-43ef-88a3-d1c0fe3ee083.jpg',true) on conflict (slug) do nothing;
insert into public.categories (slug,name,description,image,is_active) values ('combo-deals','Combo Deals','Curated pairings at a kinder price.','/faaaf0cd-fa17-45f6-bb91-31c63d521ce5.jpg',true) on conflict (slug) do nothing;
insert into public.categories (slug,name,description,image,is_active) values ('gift-sets','Gift Sets','Ready-to-give sets for birthdays, weddings and thank-yous.','/faaaf0cd-fa17-45f6-bb91-31c63d521ce5.jpg',true) on conflict (slug) do nothing;
insert into public.categories (slug,name,description,image,is_active) values ('gift-boxes','Gift Boxes','Hand-packed boxes finished with ribbon and a note card.','/faaaf0cd-fa17-45f6-bb91-31c63d521ce5.jpg',true) on conflict (slug) do nothing;
insert into public.categories (slug,name,description,image,is_active) values ('diffusers','Diffusers','Reed diffusers that hold a room in scent for months.','/2c02ed84-d86e-4549-a2f7-685bd1395d33.jpg',true) on conflict (slug) do nothing;
insert into public.categories (slug,name,description,image,is_active) values ('scented-candles','Scented Candles','Hand-poured soy candles with a warm, even throw.','/e6f6428a-544d-4c3c-a210-cb5edf3c0030.jpg',true) on conflict (slug) do nothing;
insert into public.categories (slug,name,description,image,is_active) values ('miniatures','Miniatures','Travel-size bottles — try before you commit.','/dfba970f-1742-43ef-88a3-d1c0fe3ee083.jpg',true) on conflict (slug) do nothing;
insert into public.categories (slug,name,description,image,is_active) values ('under-20k','Under ₦20k','Beautiful scent that stays within budget.','/13d0cd31-7b4e-49b1-a1c2-aa624fa6ae1d.jpg',true) on conflict (slug) do nothing;

insert into public.products (slug,name,brand_line,description,notes,price,compare_at_price,size,images,category_slugs,stock,is_new_arrival,is_best_seller,is_active,rating,review_count) values ('motun-noir-eau-de-parfum','Motun Noir','Signature Collection','Our house signature. A velvet trail of Nigerian oud, smoked vanilla and dark plum that settles into the skin and lingers long after you leave the room.','{"top":["Black plum","Bergamot"],"heart":["Rose absolute","Saffron"],"base":["Oud","Smoked vanilla","Amber"]}'::jsonb,78000,92000,'100ml',array['/114886d9-688e-4210-83f9-bea62727678e.jpg','/faebb927-96b3-4242-b079-a3a54a804b67.jpg','/faaaf0cd-fa17-45f6-bb91-31c63d521ce5.jpg']::text[],array['unisex','designer-perfume']::text[],24,false,true,true,4.9,214) on conflict (slug) do nothing;
insert into public.products (slug,name,brand_line,description,notes,price,compare_at_price,size,images,category_slugs,stock,is_new_arrival,is_best_seller,is_active,rating,review_count) values ('ivory-bloom-eau-de-parfum','Ivory Bloom','Signature Collection','A soft, luminous floral built on Nigerian frangipani and white peony, finished with a powdery musk that feels like clean linen in the sun.','{"top":["Pear nectar","Pink pepper"],"heart":["White peony","Frangipani"],"base":["Cashmere musk","Sandalwood"]}'::jsonb,64000,null,'100ml',array['/e3a59ab0-5771-43a5-9155-550dc7a4670a.jpg','/114886d9-688e-4210-83f9-bea62727678e.jpg','/faaaf0cd-fa17-45f6-bb91-31c63d521ce5.jpg']::text[],array['for-her']::text[],18,false,true,true,4.8,168) on conflict (slug) do nothing;
insert into public.products (slug,name,brand_line,description,notes,price,compare_at_price,size,images,category_slugs,stock,is_new_arrival,is_best_seller,is_active,rating,review_count) values ('harmattan-gold','Harmattan Gold','Signature Collection','Dry, golden and warm — inspired by harmattan mornings in Lagos. Toasted almond and honeyed tobacco over a resinous amber base.','{"top":["Toasted almond","Cardamom"],"heart":["Honeyed tobacco","Orris"],"base":["Benzoin","Amber","Cedar"]}'::jsonb,71500,null,'75ml',array['/faebb927-96b3-4242-b079-a3a54a804b67.jpg','/114886d9-688e-4210-83f9-bea62727678e.jpg']::text[],array['unisex','for-him']::text[],9,true,true,true,4.7,91) on conflict (slug) do nothing;
insert into public.products (slug,name,brand_line,description,notes,price,compare_at_price,size,images,category_slugs,stock,is_new_arrival,is_best_seller,is_active,rating,review_count) values ('oud-royale-pour-homme','Oud Royale Pour Homme','Designer','A commanding leather and oud composition for evening wear. Deep, dry and unmistakably masculine.','{"top":["Grapefruit","Nutmeg"],"heart":["Leather","Clary sage"],"base":["Oud","Vetiver","Patchouli"]}'::jsonb,96000,110000,'100ml',array['/114886d9-688e-4210-83f9-bea62727678e.jpg','/faebb927-96b3-4242-b079-a3a54a804b67.jpg']::text[],array['for-him','designer-perfume']::text[],6,false,true,true,4.6,77) on conflict (slug) do nothing;
insert into public.products (slug,name,brand_line,description,notes,price,compare_at_price,size,images,category_slugs,stock,is_new_arrival,is_best_seller,is_active,rating,review_count) values ('velvet-hibiscus','Velvet Hibiscus','Signature Collection','Juicy hibiscus and blackcurrant wrapped in creamy tonka. Playful in the first hour, sensual by the third.','{"top":["Hibiscus","Blackcurrant"],"heart":["Jasmine sambac","Peach"],"base":["Tonka bean","Vanilla"]}'::jsonb,58500,null,'50ml',array['/e3a59ab0-5771-43a5-9155-550dc7a4670a.jpg','/faaaf0cd-fa17-45f6-bb91-31c63d521ce5.jpg']::text[],array['for-her']::text[],31,true,false,true,4.8,63) on conflict (slug) do nothing;
insert into public.products (slug,name,brand_line,description,notes,price,compare_at_price,size,images,category_slugs,stock,is_new_arrival,is_best_seller,is_active,rating,review_count) values ('lagos-midnight','Lagos Midnight','City Series','The city after dark — salt air, spiced rum and warm skin musk. A bold unisex evening scent.','{"top":["Sea salt","Mandarin"],"heart":["Spiced rum","Iris"],"base":["Skin musk","Labdanum"]}'::jsonb,69000,null,'75ml',array['/faebb927-96b3-4242-b079-a3a54a804b67.jpg','/114886d9-688e-4210-83f9-bea62727678e.jpg']::text[],array['unisex']::text[],0,true,false,true,4.5,42) on conflict (slug) do nothing;
insert into public.products (slug,name,brand_line,description,notes,price,compare_at_price,size,images,category_slugs,stock,is_new_arrival,is_best_seller,is_active,rating,review_count) values ('rose-de-motun-body-mist','Rose de Motun Body Mist','Everyday','A weightless rose and lychee mist to layer over lotion or refresh through the day.','{"top":["Lychee","Bergamot"],"heart":["Damask rose"],"base":["White musk"]}'::jsonb,14500,null,'250ml',array['/13d0cd31-7b4e-49b1-a1c2-aa624fa6ae1d.jpg','/e3a59ab0-5771-43a5-9155-550dc7a4670a.jpg']::text[],array['body-mist','for-her','under-20k']::text[],64,false,true,true,4.7,289) on conflict (slug) do nothing;
insert into public.products (slug,name,brand_line,description,notes,price,compare_at_price,size,images,category_slugs,stock,is_new_arrival,is_best_seller,is_active,rating,review_count) values ('vanilla-sun-body-mist','Vanilla Sun Body Mist','Everyday','Warm vanilla and coconut water — the easiest scent in your bag.','{"top":["Coconut water"],"heart":["Vanilla orchid"],"base":["Soft amber"]}'::jsonb,12500,null,'250ml',array['/13d0cd31-7b4e-49b1-a1c2-aa624fa6ae1d.jpg']::text[],array['body-mist','under-20k']::text[],48,true,false,true,4.6,131) on conflict (slug) do nothing;
insert into public.products (slug,name,brand_line,description,notes,price,compare_at_price,size,images,category_slugs,stock,is_new_arrival,is_best_seller,is_active,rating,review_count) values ('citrus-drift-body-spray','Citrus Drift Body Spray','Everyday','A crisp lime, mint and cedar spray built for Lagos heat. Generous, fast-drying and long-wearing.','{"top":["Lime","Mint"],"heart":["Green apple"],"base":["Cedar"]}'::jsonb,9500,null,'200ml',array['/13d0cd31-7b4e-49b1-a1c2-aa624fa6ae1d.jpg','/faebb927-96b3-4242-b079-a3a54a804b67.jpg']::text[],array['body-sprays','under-20k','for-him']::text[],87,false,false,true,4.4,96) on conflict (slug) do nothing;
insert into public.products (slug,name,brand_line,description,notes,price,compare_at_price,size,images,category_slugs,stock,is_new_arrival,is_best_seller,is_active,rating,review_count) values ('amber-musk-body-spray','Amber Musk Body Spray','Everyday','A soft amber and musk spray that layers beautifully under any of our parfums.','{"top":["Pink pepper"],"heart":["Amber"],"base":["White musk","Vanilla"]}'::jsonb,10500,null,'200ml',array['/13d0cd31-7b4e-49b1-a1c2-aa624fa6ae1d.jpg']::text[],array['body-sprays','under-20k','unisex']::text[],52,false,false,true,4.3,58) on conflict (slug) do nothing;
insert into public.products (slug,name,brand_line,description,notes,price,compare_at_price,size,images,category_slugs,stock,is_new_arrival,is_best_seller,is_active,rating,review_count) values ('attar-noir-perfume-oil','Attar Noir Perfume Oil','Oil Collection','Alcohol-free concentrated oil of oud, rose and sandalwood. One roll on the wrist lasts the whole day.','{"top":["Saffron"],"heart":["Taif rose"],"base":["Oud","Sandalwood"]}'::jsonb,22000,null,'12ml',array['/dfba970f-1742-43ef-88a3-d1c0fe3ee083.jpg','/114886d9-688e-4210-83f9-bea62727678e.jpg']::text[],array['perfume-oils','unisex']::text[],27,false,true,true,4.9,143) on conflict (slug) do nothing;
insert into public.products (slug,name,brand_line,description,notes,price,compare_at_price,size,images,category_slugs,stock,is_new_arrival,is_best_seller,is_active,rating,review_count) values ('shea-vanilla-perfume-oil','Shea & Vanilla Perfume Oil','Oil Collection','Nutty shea butter accord over Madagascan vanilla. Comforting, skin-close and gently sweet.','{"top":["Almond milk"],"heart":["Shea accord"],"base":["Madagascan vanilla","Tonka"]}'::jsonb,18000,null,'12ml',array['/dfba970f-1742-43ef-88a3-d1c0fe3ee083.jpg']::text[],array['perfume-oils','for-her','under-20k']::text[],40,true,false,true,4.7,74) on conflict (slug) do nothing;
insert into public.products (slug,name,brand_line,description,notes,price,compare_at_price,size,images,category_slugs,stock,is_new_arrival,is_best_seller,is_active,rating,review_count) values ('the-duo-combo','The Duo — Parfum + Body Mist','Combo','Pair any signature parfum with its matching body mist and save. Layering made simple.','{"top":["Varies"],"heart":["Varies"],"base":["Varies"]}'::jsonb,74000,92500,'100ml + 250ml',array['/faaaf0cd-fa17-45f6-bb91-31c63d521ce5.jpg','/13d0cd31-7b4e-49b1-a1c2-aa624fa6ae1d.jpg']::text[],array['combo-deals']::text[],15,false,true,true,4.8,88) on conflict (slug) do nothing;
insert into public.products (slug,name,brand_line,description,notes,price,compare_at_price,size,images,category_slugs,stock,is_new_arrival,is_best_seller,is_active,rating,review_count) values ('his-hers-combo','His & Hers Combo','Combo','Motun Noir and Ivory Bloom together — our most gifted pairing for couples.','{"top":["Varies"],"heart":["Varies"],"base":["Varies"]}'::jsonb,128000,142000,'2 × 100ml',array['/faaaf0cd-fa17-45f6-bb91-31c63d521ce5.jpg','/faebb927-96b3-4242-b079-a3a54a804b67.jpg']::text[],array['combo-deals','gift-sets']::text[],11,false,false,true,4.9,51) on conflict (slug) do nothing;
insert into public.products (slug,name,brand_line,description,notes,price,compare_at_price,size,images,category_slugs,stock,is_new_arrival,is_best_seller,is_active,rating,review_count) values ('the-motun-discovery-set','The Motun Discovery Set','Gifting','Five 10ml miniatures of our best-loved scents in a keepsake box. The best way to find your signature.','{"top":["Varies"],"heart":["Varies"],"base":["Varies"]}'::jsonb,34000,null,'5 × 10ml',array['/faaaf0cd-fa17-45f6-bb91-31c63d521ce5.jpg','/dfba970f-1742-43ef-88a3-d1c0fe3ee083.jpg']::text[],array['gift-sets','miniatures']::text[],22,true,true,true,4.9,197) on conflict (slug) do nothing;
insert into public.products (slug,name,brand_line,description,notes,price,compare_at_price,size,images,category_slugs,stock,is_new_arrival,is_best_seller,is_active,rating,review_count) values ('celebration-gift-box','Celebration Gift Box','Gifting','A parfum, a candle and a hand-written note card, packed in our ribboned brown keepsake box.','{"top":["Varies"],"heart":["Varies"],"base":["Varies"]}'::jsonb,89000,null,'Box set',array['/faaaf0cd-fa17-45f6-bb91-31c63d521ce5.jpg','/e6f6428a-544d-4c3c-a210-cb5edf3c0030.jpg']::text[],array['gift-boxes','gift-sets']::text[],8,false,false,true,4.8,39) on conflict (slug) do nothing;
insert into public.products (slug,name,brand_line,description,notes,price,compare_at_price,size,images,category_slugs,stock,is_new_arrival,is_best_seller,is_active,rating,review_count) values ('bridal-gift-box','Bridal Gift Box','Gifting','Curated for the bride — Ivory Bloom parfum, matching oil and a soy candle in ivory wrapping.','{"top":["Varies"],"heart":["Varies"],"base":["Varies"]}'::jsonb,112000,null,'Box set',array['/faaaf0cd-fa17-45f6-bb91-31c63d521ce5.jpg','/e3a59ab0-5771-43a5-9155-550dc7a4670a.jpg']::text[],array['gift-boxes','for-her']::text[],5,true,false,true,5,24) on conflict (slug) do nothing;
insert into public.products (slug,name,brand_line,description,notes,price,compare_at_price,size,images,category_slugs,stock,is_new_arrival,is_best_seller,is_active,rating,review_count) values ('amber-oud-reed-diffuser','Amber Oud Reed Diffuser','Home','Eight rattan reeds in smoked amber glass. Holds a living room in warm oud for up to four months.','{"top":["Bergamot"],"heart":["Amber"],"base":["Oud","Cedarwood"]}'::jsonb,27500,null,'200ml',array['/2c02ed84-d86e-4549-a2f7-685bd1395d33.jpg','/e6f6428a-544d-4c3c-a210-cb5edf3c0030.jpg']::text[],array['diffusers']::text[],19,false,false,true,4.6,47) on conflict (slug) do nothing;
insert into public.products (slug,name,brand_line,description,notes,price,compare_at_price,size,images,category_slugs,stock,is_new_arrival,is_best_seller,is_active,rating,review_count) values ('jasmine-tea-reed-diffuser','Jasmine Tea Reed Diffuser','Home','Green tea and jasmine — a lighter, brighter option for bedrooms and studies.','{"top":["Green tea"],"heart":["Jasmine"],"base":["Soft musk"]}'::jsonb,24000,null,'200ml',array['/2c02ed84-d86e-4549-a2f7-685bd1395d33.jpg']::text[],array['diffusers']::text[],0,false,false,true,4.4,21) on conflict (slug) do nothing;
insert into public.products (slug,name,brand_line,description,notes,price,compare_at_price,size,images,category_slugs,stock,is_new_arrival,is_best_seller,is_active,rating,review_count) values ('brown-sugar-oud-candle','Brown Sugar & Oud Candle','Home','Hand-poured soy wax with a cotton wick. Burns clean for 45 hours with a deep, even throw.','{"top":["Brown sugar"],"heart":["Clove"],"base":["Oud","Vanilla"]}'::jsonb,19500,null,'220g',array['/e6f6428a-544d-4c3c-a210-cb5edf3c0030.jpg','/2c02ed84-d86e-4549-a2f7-685bd1395d33.jpg']::text[],array['scented-candles','under-20k']::text[],36,false,true,true,4.8,156) on conflict (slug) do nothing;
insert into public.products (slug,name,brand_line,description,notes,price,compare_at_price,size,images,category_slugs,stock,is_new_arrival,is_best_seller,is_active,rating,review_count) values ('coconut-shea-candle','Coconut & Shea Candle','Home','Creamy coconut over toasted shea. A softer, sweeter candle for open living spaces.','{"top":["Coconut"],"heart":["Shea accord"],"base":["Sandalwood"]}'::jsonb,17500,null,'220g',array['/e6f6428a-544d-4c3c-a210-cb5edf3c0030.jpg']::text[],array['scented-candles','under-20k']::text[],29,true,false,true,4.5,68) on conflict (slug) do nothing;
insert into public.products (slug,name,brand_line,description,notes,price,compare_at_price,size,images,category_slugs,stock,is_new_arrival,is_best_seller,is_active,rating,review_count) values ('motun-noir-miniature','Motun Noir Miniature','Miniatures','The full Motun Noir experience in a 10ml purse spray. Refillable and travel-safe.','{"top":["Black plum"],"heart":["Rose absolute"],"base":["Oud","Smoked vanilla"]}'::jsonb,15000,null,'10ml',array['/dfba970f-1742-43ef-88a3-d1c0fe3ee083.jpg','/114886d9-688e-4210-83f9-bea62727678e.jpg']::text[],array['miniatures','under-20k','unisex']::text[],73,false,true,true,4.9,204) on conflict (slug) do nothing;
insert into public.products (slug,name,brand_line,description,notes,price,compare_at_price,size,images,category_slugs,stock,is_new_arrival,is_best_seller,is_active,rating,review_count) values ('ivory-bloom-miniature','Ivory Bloom Miniature','Miniatures','Our bestselling floral, sized for a handbag.','{"top":["Pear nectar"],"heart":["White peony"],"base":["Cashmere musk"]}'::jsonb,13500,null,'10ml',array['/dfba970f-1742-43ef-88a3-d1c0fe3ee083.jpg','/e3a59ab0-5771-43a5-9155-550dc7a4670a.jpg']::text[],array['miniatures','under-20k','for-her']::text[],58,false,false,true,4.7,112) on conflict (slug) do nothing;
insert into public.products (slug,name,brand_line,description,notes,price,compare_at_price,size,images,category_slugs,stock,is_new_arrival,is_best_seller,is_active,rating,review_count) values ('blanc-de-luxe-designer','Blanc de Luxe','Designer','A crisp designer classic — aldehydic citrus over iris and blonde woods. Sealed and authenticity-checked.','{"top":["Aldehydes","Lemon"],"heart":["Iris","Neroli"],"base":["Blonde woods","Musk"]}'::jsonb,145000,168000,'100ml',array['/faebb927-96b3-4242-b079-a3a54a804b67.jpg','/114886d9-688e-4210-83f9-bea62727678e.jpg']::text[],array['designer-perfume','for-her']::text[],4,true,false,true,4.8,33) on conflict (slug) do nothing;
insert into public.products (slug,name,brand_line,description,notes,price,compare_at_price,size,images,category_slugs,stock,is_new_arrival,is_best_seller,is_active,rating,review_count) values ('terre-boisee-designer','Terre Boisée','Designer','Earthy vetiver and dry grapefruit — a refined designer daily driver for him.','{"top":["Grapefruit"],"heart":["Vetiver","Geranium"],"base":["Cedar","Benzoin"]}'::jsonb,132000,null,'100ml',array['/faebb927-96b3-4242-b079-a3a54a804b67.jpg']::text[],array['designer-perfume','for-him']::text[],7,false,false,true,4.6,45) on conflict (slug) do nothing;
insert into public.products (slug,name,brand_line,description,notes,price,compare_at_price,size,images,category_slugs,stock,is_new_arrival,is_best_seller,is_active,rating,review_count) values ('archive-fig-parfum','Archive Fig','Archive','A discontinued favourite kept in the archive — green fig, coconut milk and warm stone.','{"top":["Fig leaf"],"heart":["Coconut milk"],"base":["Warm stone","Cedar"]}'::jsonb,61000,null,'75ml',array['/114886d9-688e-4210-83f9-bea62727678e.jpg']::text[],array['unisex']::text[],3,false,false,false,4.5,18) on conflict (slug) do nothing;

insert into public.coupons (code,type,value,min_spend,usage_limit,times_used,expires_at,is_active) values ('MOTUN10','percent',10,30000,500,213,'2026-12-31',true) on conflict (code) do nothing;
insert into public.coupons (code,type,value,min_spend,usage_limit,times_used,expires_at,is_active) values ('WELCOME5K','fixed',5000,50000,200,88,'2026-10-31',true) on conflict (code) do nothing;
insert into public.coupons (code,type,value,min_spend,usage_limit,times_used,expires_at,is_active) values ('GIFTING15','percent',15,100000,100,41,'2026-09-30',true) on conflict (code) do nothing;
insert into public.coupons (code,type,value,min_spend,usage_limit,times_used,expires_at,is_active) values ('EASTER20','percent',20,25000,300,300,'2026-04-30',false) on conflict (code) do nothing;

insert into public.testimonials (name,location,rating,quote,status,created_at) select 'Adaeze Okonkwo','Lekki, Lagos',5,'Motun Noir is the first perfume anyone has ever stopped me to ask about — three times in one week. The projection is unreal for the price.','approved','2026-06-11T09:12:00.000Z' where not exists (select 1 from public.testimonials where quote = 'Motun Noir is the first perfume anyone has ever stopped me to ask about — three times in one week. The projection is unreal for the price.');
insert into public.testimonials (name,location,rating,quote,status,created_at) select 'Fatima Bello','Maitama, Abuja',5,'I ordered the Discovery Set to find my signature and ended up buying full bottles of two. Packaging felt like a gift to myself.','approved','2026-06-28T14:40:00.000Z' where not exists (select 1 from public.testimonials where quote = 'I ordered the Discovery Set to find my signature and ended up buying full bottles of two. Packaging felt like a gift to myself.');
insert into public.testimonials (name,location,rating,quote,status,created_at) select 'Chidinma Eze','Port Harcourt',4,'Delivery to PH took two days and the bottle arrived perfectly wrapped. Ivory Bloom lasts a full work day on me.','approved','2026-07-03T18:05:00.000Z' where not exists (select 1 from public.testimonials where quote = 'Delivery to PH took two days and the bottle arrived perfectly wrapped. Ivory Bloom lasts a full work day on me.');
insert into public.testimonials (name,location,rating,quote,status,created_at) select 'Tunde Ajayi','Ikeja, Lagos',5,'Bought the His & Hers combo for our anniversary. My wife has not stopped wearing hers. Customer service on WhatsApp was instant.','approved','2026-07-15T11:22:00.000Z' where not exists (select 1 from public.testimonials where quote = 'Bought the His & Hers combo for our anniversary. My wife has not stopped wearing hers. Customer service on WhatsApp was instant.');
insert into public.testimonials (name,location,rating,quote,status,created_at) select 'Zainab Yusuf','Kano',5,'The Attar Noir oil is the closest thing to what I used to buy abroad, and it lasts longer. Reordering already.','pending','2026-07-24T08:33:00.000Z' where not exists (select 1 from public.testimonials where quote = 'The Attar Noir oil is the closest thing to what I used to buy abroad, and it lasts longer. Reordering already.');
insert into public.testimonials (name,location,rating,quote,status,created_at) select 'Ngozi Umeh','Enugu',3,'Lovely scent but I wish the body mist came in a bigger size. Still, good value.','pending','2026-07-29T16:58:00.000Z' where not exists (select 1 from public.testimonials where quote = 'Lovely scent but I wish the body mist came in a bigger size. Still, good value.');

insert into public.store_locations (name,address,city,hours,phone) select 'Scent by Motun — Lekki Flagship','14b Admiralty Way, Lekki Phase 1','Lagos','Mon – Sat, 9:00am – 8:00pm','+234 803 000 1122' where not exists (select 1 from public.store_locations where name = 'Scent by Motun — Lekki Flagship');
insert into public.store_locations (name,address,city,hours,phone) select 'Scent by Motun — Ikeja Counter','Shop 42, Ikeja City Mall, Alausa','Lagos','Mon – Sun, 10:00am – 9:00pm','+234 803 000 3344' where not exists (select 1 from public.store_locations where name = 'Scent by Motun — Ikeja Counter');
insert into public.store_locations (name,address,city,hours,phone) select 'Scent by Motun — Abuja Studio','7 Gana Street, Maitama','Abuja','Mon – Fri, 10:00am – 6:00pm','+234 803 000 5566' where not exists (select 1 from public.store_locations where name = 'Scent by Motun — Abuja Studio');
